development:
  adapter: postgresql
  encoding: utf8
  database: kenjiboard_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: kenjiboard_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: kenjiboard_production
  pool: 5
  username:
  password:
